Traceback (most recent call last):
  File "maskcreate.py", line 53, in <module>
    f = fits.open(sys.argv[1]) #sys.argv[1] = VCC????-I-Flag.fits
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 998, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'VCC0725-I-Flag.fits'
Traceback (most recent call last):
  File "pixel-flag-flip.py", line 14, in <module>
    f = fits.open(sys.argv[1]) #sys.argv[1] = VCC????-I-Flag.fits
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 998, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'VCC0725-I-Flag.fits'
Traceback (most recent call last):
  File "maskcreate.py", line 53, in <module>
    f = fits.open(sys.argv[1]) #sys.argv[1] = VCC????-I-Flag.fits
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 998, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'VCC0725-I-Flag.fits'
Traceback (most recent call last):
  File "pixel-flag-flip.py", line 14, in <module>
    f = fits.open(sys.argv[1]) #sys.argv[1] = VCC????-I-Flag.fits
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 160, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 413, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 998, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/home/matt/anaconda3/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'VCC0725-I-Flag.fits'
